server:
  port: 9000

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    ip-address: ${COMMON}
    hostname: ${COMMON}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://43.201.164.202:8761/eureka

spring:
  application:
    name: common
  config:
    name: common
    import: optional:configserver:http://43.202.20.179:8888

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans