server:
  port: 9003

spring:
  application:
    name: crawling
  config:
    name: crawling

  profiles:
    active: prod

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: ${CRAWLING}
    ip-address: ${CRAWLING}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${SERVICE-DISCOVERY}:8761/eureka

---

spring:
  config:
    import: optional:configserver:http://43.202.20.179:8888
    activate:
      on-profile: prod


---

spring:
  config:
    import: optional:configserver:http://localhost:8888
    activate:
      on-profile: local
