server:
  port: 8000

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://service-discovery:8761/eureka

spring:
  application:
    name: api-gateway
  config:
    name: api-gateway
    import: optional:configserver:http://config:8888

management:
  endpoint:
    refresh:
      enabled: true