server:
  port: 9001

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: ${CHAT}
    ip-address: ${CHAT}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://43.201.164.202:8761/eureka

spring:
  application:
    name: api-gateway
  config:
    name: api-gateway
    import: optional:configserver:http://43.202.20.179:8888

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans

message: ${message}